### ISSUE TITLE
Compatibility Issues in Pale Moon Browser (Firefox Fork)

### ISSUE THREAD

**Issue by noellarkin** [AykutCevik/Geolocate-IP-Browser-Extension#22]
Hey!

Thanks for the amazing work on this plugin, I've used it on Firefox and it works really well. However, I've recently shifted to Pale Moon browser (which is a fork of Firefox) and the extension isn't working on Pale Moon.

It seems that Pale Moon, and many related browsers (Basilisk, Sea Monkey, IceCat, K Meleon) use the XUL framework, as opposed to WebExtensions.

I'd really appreciate it if you could make a Pale Moon compatible plugin. I'd love to be able to continue using your plugin.

Thanks again.,

Noel

**Comment by AykutCevik** [comment]
Hello @noellarkin,

Thank you for your kind words and I'm happy that you like the extension.

Due to the little time I have for these small projects, I won't be able to write a XUL compatible version of this extension.

Nevertheless I will check if it could be possible to use this version with small modifications to make it compatible.

**Comment by AykutCevik** [comment]
It doesn't seem that this will be easy and fast to solve. Will close this, but feel free to implement it and to make a PR. Thanks for your participation already @noellarkin!
